name: Deploy HTML

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    paths:
    - '**.html'
    - '.github/workflows/deploy.yml'
  workflow_dispatch:
    
concurrency:
  group: pages
  cancel-in-progress: false

jobs:

  deploy:
    environment:
      name: docs
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: .
      - uses: actions/deploy-pages@v2
        id: deployment